[#ftl]
[@b.head/]
[@b.toolbar title="修改专业"]bar.addBack();[/@]
[@b.tabs]
  [@b.tab label="基本信息"]
  [#assign sa][#if major.id??]!update?id=${major.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="major.code" label="代码" value="${major.code!}" required="true" maxlength="20"/]
    [@b.textfield name="major.name" label="名称" value="${major.name!}" required="true" maxlength="20"/]
    [@b.textfield name="major.enName" label="英文名" value="${major.enName!}" maxlength="100"/]
    [@b.textfield name="major.shortName" label="简称" value="${major.shortName!}" maxlength="100"/]
    [@b.select name="major.project.id" label="项目名称" value="${(major.project.id)!}" required="true" 
               style="width:200px;" items=projects option="id,name" empty="..."/]
    [@b.startend label="生效失效时间" 
      name="major.beginOn,major.endOn" required="false,false" 
      start=major.beginOn end=major.endOn format="date"/]
    [@b.textfield name="major.remark" label="备注" value="${major.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
   [/@]
 [/@]
  [#if major.id??]
	  [@b.tab label="建设过程"]
	  [@b.div href="major-journal!search?majorJournal.major.id=${major.id}"/]
	   [/@]
    [@b.tab label="专业学科信息"]
    [@b.div href="major-discipline!search?majorDiscipline.major.id=${major.id}"/]
     [/@]
  [/#if]
  [/@]
[@b.foot/]