[#ftl]
[@b.head/]
[@b.grid items=majors var="major"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="code" title="代码"]${major.code}[/@]
    [@b.col width="20%" property="name" title="名称"][@b.a href="!info?id=${major.id}"]${major.name}[/@][/@]
    [@b.col width="20%" property="enName" title="英文名"]${major.enName!}[/@]
    [@b.col width="20%" title="部门"]
    [#assign departs = [] /]
    [#list major.journals as j][#if !(j.endOn??) && !departs?seq_contains(j.depart)][#assign departs = departs+[j.depart]][/#if][/#list]
    [#list departs as d]${d.name}[#if d_has_next] [/#if][/#list]
    [/@]
    [@b.col width="10%" title="培养层次"]
    [#assign educations = [] /]
    [#list major.journals as j][#if !(j.endOn??) && !educations?seq_contains(j.education)][#assign educations = educations+[j.education]][/#if][/#list]
    [#list educations as d]${d.name}[#if d_has_next] [/#if][/#list]
    [/@]
    [@b.col width="10%" title="学科"]
    [#assign categories = [] /]
    [#list major.disciplines as d][#if !(d.endOn??) && (d.category??) && !categories?seq_contains(d.category)][#assign categories = categories+[d.category]][/#if][/#list]
    [#list categories as d]${d.name}[#if d_has_next] [/#if][/#list]
    [/@]
  [/@]
[/@]
[@b.foot/]
