[#ftl]
[@b.head/]
[@b.grid items=majorJournals var="majorJournal"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="15%" property="education" title="培养层次"]${(majorJournal.education.name)!}[/@]
    [@b.col width="15%" property="education" title="专业"]${(majorJournal.major.name)!}[/@]
    [@b.col width="15%" property="depart" title="部门"]${(majorJournal.depart.name)!}[/@]
    [@b.col width="15%" property="duration" title="修读年限"]${majorJournal.duration}[/@]
    [@b.col width="10%" property="beginOn" title="生效时间"]${majorJournal.beginOn!}[/@]
    [@b.col width="10%" property="endOn" title="失效时间"]${majorJournal.endOn!}[/@]
    [@b.col width="10%" property="endOn" title="备注"]${majorJournal.remark!}[/@]
  [/@]
[/@]
[@b.foot/]
