[#ftl]
[@b.head/]
[@b.toolbar title="修改教师信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(teacher) theme="list"]
    [@b.field label="职工号"]${teacher.user.code!}[/@]
    [@b.field label="姓名"]${teacher.user.name!}[/@]
    [@b.field label="部门"]${teacher.user.department.name}[/@]
    [@b.select name="teacher.teacherType.id" label="教师类型" value="" required="true" style="width:200px;" items=teacherTypes option="id,name" empty="..."/]
    [@b.startend label="任教时间" name="teacher.beginOn,teacher.endOn" required="true,false" start=teacher.beginOn end=teacher.endOn format="date"/]
    [@b.textfield name="teacher.remark" label="备注" value="${teacher.remark!}" maxlength="30"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]