[#ftl]
[@b.head/]
[@b.grid items=courses var="course"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="code" title="代码"]${course.code}[/@]
    [@b.col width="15%" property="name" title="名称"][@b.a href="!info?id=${course.id}"]${course.name}[/@][/@]
    [@b.col width="10%" property="code" title="学时"]${course.period!}[/@]
    [@b.col width="10%" property="code" title="周课时"]${course.weekHour!}[/@]
    [@b.col width="10%" property="credits" title="学分"]${course.credits!}[/@]
    [@b.col width="15%" property="department" title="院系"]${(course.department.name)!}[/@]
    [@b.col width="30%" property="code" title="英文名"]${course.enName!}[/@]
  [/@]
  [/@]
[@b.foot/]
