[#ftl]
[@b.head/]
[@b.toolbar title="修改课程分类课时信息"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if courseHour.persisted]!update?id=${courseHour.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.select name="courseHour.course.id" label="对应课程" value="${(courseHour.course.id)!}" required="true" 
               style="width:200px;" items=courses option="id,name" empty="..."/]
    [@b.textfield name="courseHour.period" label="学时" value="${courseHour.period!}" maxlength="30"/]
    [@b.textfield name="courseHour.weekHour" label="周课时" value="${courseHour.weekHour!}" maxlength="30"/]
    [@b.textfield name="courseHour.weeks" label="周数" value="${courseHour.weeks!}" maxlength="30"/]               
    [@b.select name="courseHour.hourType.id" label="课时类别代码" value="${(courseHour.hourType.id)!}" required="true" 
               style="width:200px;" items=hourTypes option="id,name" empty="..."/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]